apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  labels:
    app: notes
spec:
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: ghcr.io/tuna2134/notes
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: HOSTNAME
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: notes
spec:
  selector:
    app: notes
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
